title: "Niklas Müller"
author: "Niklas Müller"
description: "Copyright 2025 Niklas Müller"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

collections:
  publications:
    output: true
  news:
    output: true
  cv:
    output: true

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {url: "publications", title: "Publications"}
  - {url: "news", title: "News & Events"}
  - {file: "cv.md", title: "CV"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: "Mail (n.muller@uva.nl)", icon: envelope, url: "mailto:n.muller@uva.nl"}
  - {title: "University of Amsterdam", icon: map, url: "https://www.uva.nl/profiel/m/u/n.muller/n.muller.html"}
  - {title: Github, icon: github, url: "https://github.com/niklas-mueller"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/niklas-mueller12/"}
  - {title: Scholar, icon: graduation-cap, url: "https://scholar.google.com/citations?user=GxMPblkAAAAJ&hl=en"}
  - {title: ORCID, icon: orcid, url: "https://orcid.org/0009-0001-9281-9296"}


comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
 - jekyll-academicons-svg
 - jekyll-paginate-v2

# pagination:
#   enabled: true
#   per_page: 2
#   title: ':title - page :num'
#   limit: 0
#   sort_field: 'date'
#   sort_reverse: true
#   trail:
#     before: 2
#     after: 2